version: '3.8'

services:
  ecopaste_cloud:
    image: mrtian2016/ecopaste:latest
    container_name: ecopaste_cloud
    restart: unless-stopped
    volumes:
      - ./data:/ecopaste
    ports:
      - "5280:5280"

  
